192.168.137.1 - - [07/Jan/2020 10:03:51] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py:21: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(14, GPIO.OUT)
192.168.137.1 - - [07/Jan/2020 10:03:53] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py:21: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(14, GPIO.OUT)
192.168.137.1 - - [07/Jan/2020 10:05:08] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py:21: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(14, GPIO.OUT)
192.168.137.1 - - [07/Jan/2020 10:07:52] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:07:52] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:07:56] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:07:56] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:08:11] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:08:11] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:08:36] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:08:36] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:08:36] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:08:36] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:08:36] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:08:36] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:08:37] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:08:37] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:09:14] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 293, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
192.168.137.1 - - [07/Jan/2020 10:09:15] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:09:15] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:09:16] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:09:17] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:10:51] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:10:51] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:10:53] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:10:53] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:10:54] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:10:54] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:10:54] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:10:54] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:10:54] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:10:54] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:10:54] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:10:54] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:10:55] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:10:55] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:10:55] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:10:55] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:10:55] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:10:55] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:10:55] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:10:55] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:10:55] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:10:55] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:11:08] "POST /cgi-bin/webled.py HTTP/1.1" 200 -
/home/pi/task5/syspro2019_chapter6/cgi-bin/webled.py:19: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(14, GPIO.OUT)
192.168.137.1 - - [07/Jan/2020 10:11:10] "POST /cgi-bin/webled.py HTTP/1.1" 200 -
/home/pi/task5/syspro2019_chapter6/cgi-bin/webled.py:19: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(14, GPIO.OUT)
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
192.168.137.1 - - [07/Jan/2020 10:11:10] "POST /cgi-bin/webled.py HTTP/1.1" 200 -
/home/pi/task5/syspro2019_chapter6/cgi-bin/webled.py:19: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(14, GPIO.OUT)
192.168.137.1 - - [07/Jan/2020 10:11:10] "POST /cgi-bin/webled.py HTTP/1.1" 200 -
/home/pi/task5/syspro2019_chapter6/cgi-bin/webled.py:19: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(14, GPIO.OUT)
192.168.137.1 - - [07/Jan/2020 10:11:11] "POST /cgi-bin/webled.py HTTP/1.1" 200 -
/home/pi/task5/syspro2019_chapter6/cgi-bin/webled.py:19: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(14, GPIO.OUT)
192.168.137.1 - - [07/Jan/2020 10:11:11] "POST /cgi-bin/webled.py HTTP/1.1" 200 -
/home/pi/task5/syspro2019_chapter6/cgi-bin/webled.py:19: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(14, GPIO.OUT)
192.168.137.1 - - [07/Jan/2020 10:11:29] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:11:29] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:11:29] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:11:29] CGI script exit status 0x100
192.168.137.1 - - [07/Jan/2020 10:11:30] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 16
SyntaxError: Non-ASCII character '\xe9' in file /home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
192.168.137.1 - - [07/Jan/2020 10:11:30] CGI script exit status 0x100
python: can't open file '–m': [Errno 2] No such file or directory

Usage:
 kill [options] <pid> [...]

Options:
 <pid> [...]            send signal to every <pid> listed
 -<signal>, -s, --signal <signal>
                        specify the <signal> to be sent
 -l, --list=[<signal>]  list all signal names, or convert one to a name
 -L, --table            list all signal names in a nice table

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see kill(1).
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/CGIHTTPServer.py", line 378, in <module>
    test()
  File "/usr/lib/python2.7/CGIHTTPServer.py", line 374, in test
    SimpleHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 606, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
192.168.137.1 - - [14/Jan/2020 10:23:51] code 404, message File not found
192.168.137.1 - - [14/Jan/2020 10:23:51] "GET /cgi HTTP/1.1" 404 -
192.168.137.1 - - [14/Jan/2020 10:23:51] "GET / HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 293, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
192.168.137.1 - - [14/Jan/2020 10:23:51] code 404, message File not found
192.168.137.1 - - [14/Jan/2020 10:23:51] "GET /favicon.ico HTTP/1.1" 404 -
192.168.137.1 - - [14/Jan/2020 10:23:56] "GET / HTTP/1.1" 200 -
192.168.137.1 - - [14/Jan/2020 10:24:02] code 403, message CGI script is not a plain file ('/cgi-bin/')
192.168.137.1 - - [14/Jan/2020 10:24:02] "GET /cgi-bin/ HTTP/1.1" 403 -
192.168.137.1 - - [14/Jan/2020 10:24:14] code 403, message CGI script is not a plain file ('/cgi-bin/')
192.168.137.1 - - [14/Jan/2020 10:24:14] "GET /cgi-bin/ HTTP/1.1" 403 -
192.168.137.1 - - [14/Jan/2020 10:24:33] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py:5: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(2, GPIO.OUT)
Traceback (most recent call last):
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 7, in <module>
    import servo    #servo movement
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 17, in <module>
    setservo(-90)
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 9, in setservo
    servo = GPIO.PWM(2, 50)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
192.168.137.1 - - [14/Jan/2020 10:24:33] CGI script exit status 0x100
192.168.137.1 - - [14/Jan/2020 10:25:27] "GET /cgi-bin/webled.py HTTP/1.1" 200 -
192.168.137.1 - - [14/Jan/2020 10:25:29] "POST /cgi-bin/webled.py HTTP/1.1" 200 -
/home/pi/task5/syspro2019_chapter6/cgi-bin/webled.py:19: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(14, GPIO.OUT)
192.168.137.1 - - [14/Jan/2020 10:25:29] "POST /cgi-bin/webled.py HTTP/1.1" 200 -
/home/pi/task5/syspro2019_chapter6/cgi-bin/webled.py:19: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(14, GPIO.OUT)
192.168.137.1 - - [14/Jan/2020 10:25:30] "POST /cgi-bin/webled.py HTTP/1.1" 200 -
/home/pi/task5/syspro2019_chapter6/cgi-bin/webled.py:19: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(14, GPIO.OUT)
192.168.137.1 - - [14/Jan/2020 10:25:35] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 7, in <module>
    import servo    #servo movement
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 17, in <module>
    setservo(-90)
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 9, in setservo
    servo = GPIO.PWM(2, 50)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
192.168.137.1 - - [14/Jan/2020 10:25:35] CGI script exit status 0x100
192.168.137.1 - - [14/Jan/2020 10:28:08] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 7, in <module>
    import servo    #servo movement
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 17, in <module>
    setservo(-90)
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 9, in setservo
    servo = GPIO.PWM(2, 50)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
192.168.137.1 - - [14/Jan/2020 10:28:08] CGI script exit status 0x100
192.168.137.1 - - [14/Jan/2020 10:28:09] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 7, in <module>
    import servo    #servo movement
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 17, in <module>
    setservo(-90)
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 9, in setservo
    servo = GPIO.PWM(2, 50)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
192.168.137.1 - - [14/Jan/2020 10:28:09] CGI script exit status 0x100
192.168.137.1 - - [14/Jan/2020 10:28:09] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 7, in <module>
    import servo    #servo movement
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 17, in <module>
    setservo(-90)
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 9, in setservo
    servo = GPIO.PWM(2, 50)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
192.168.137.1 - - [14/Jan/2020 10:28:09] CGI script exit status 0x100
192.168.137.1 - - [14/Jan/2020 10:28:09] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 7, in <module>
    import servo    #servo movement
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 17, in <module>
    setservo(-90)
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 9, in setservo
    servo = GPIO.PWM(2, 50)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
192.168.137.1 - - [14/Jan/2020 10:28:09] CGI script exit status 0x100
192.168.137.1 - - [14/Jan/2020 10:28:09] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 7, in <module>
    import servo    #servo movement
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 17, in <module>
    setservo(-90)
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 9, in setservo
    servo = GPIO.PWM(2, 50)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
192.168.137.1 - - [14/Jan/2020 10:28:10] CGI script exit status 0x100
192.168.137.1 - - [14/Jan/2020 10:28:10] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 7, in <module>
    import servo    #servo movement
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 17, in <module>
    setservo(-90)
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 9, in setservo
    servo = GPIO.PWM(2, 50)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
192.168.137.1 - - [14/Jan/2020 10:28:10] CGI script exit status 0x100
192.168.137.1 - - [14/Jan/2020 10:28:15] "GET /cgi-bin/webled.py HTTP/1.1" 200 -
/home/pi/task5/syspro2019_chapter6/cgi-bin/webled.py:19: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(14, GPIO.OUT)
192.168.137.1 - - [14/Jan/2020 10:28:22] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 7, in <module>
    import servo    #servo movement
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 17, in <module>
    setservo(-90)
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 9, in setservo
    servo = GPIO.PWM(2, 50)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
192.168.137.1 - - [14/Jan/2020 10:28:22] CGI script exit status 0x100
192.168.137.1 - - [14/Jan/2020 10:30:30] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 7, in <module>
    import servo    #servo movement
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 17, in <module>
    setservo(-90)
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 9, in setservo
    servo = GPIO.PWM(2, 50)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
192.168.137.1 - - [14/Jan/2020 10:30:30] CGI script exit status 0x100
192.168.137.1 - - [14/Jan/2020 10:30:30] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 7, in <module>
    import servo    #servo movement
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 17, in <module>
    setservo(-90)
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 9, in setservo
    servo = GPIO.PWM(2, 50)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
192.168.137.1 - - [14/Jan/2020 10:30:30] CGI script exit status 0x100
192.168.137.1 - - [14/Jan/2020 10:30:31] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 7, in <module>
    import servo    #servo movement
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 17, in <module>
    setservo(-90)
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 9, in setservo
    servo = GPIO.PWM(2, 50)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
192.168.137.1 - - [14/Jan/2020 10:30:31] CGI script exit status 0x100
192.168.137.1 - - [14/Jan/2020 10:30:31] "GET /cgi-bin/webservo.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/webservo.py", line 7, in <module>
    import servo    #servo movement
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 17, in <module>
    setservo(-90)
  File "/home/pi/task5/syspro2019_chapter6/cgi-bin/servo.py", line 9, in setservo
    servo = GPIO.PWM(2, 50)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
192.168.137.1 - - [14/Jan/2020 10:30:31] CGI script exit status 0x100
